### ISSUE TITLE
Post Issues

### ISSUE THREAD

**Issue by bubudrc** [gotranseo/template#5]
Hello, me again.. .sorry.

So, After I configure all, I will start to validate the POST calls for login/register, but, I have always the same response: FORBIDDEN

```
[ INFO ] Migrating 'mysql' database .../Sources/Fluent/Migration/MigrationConfig.swift:69)
[ INFO ] Migrations complete .../Sources/Fluent/Migration/MigrationConfig.swift:73)
Server starting on http://localhost:8080
[ ERROR ] Forbidden (.../Sources/App/Middleware/TranseoErrorMiddleware.swift:84)
```

what the `csrf` param request is? why we need?

This is the post call:
`curl -H "Content-Type: application/json" -X POST -d '{"email":"zelda@hyrule.com", "password": "link", "confirmPassword": "link", "name": "Zelda Testing", "csrf": "CSFRTest"}' http://localhost:8080/register`

**Comment by jdmcd** [comment]
That's because the /register and /login routes are meant to be executed from the frontend, where a CSRF token is passed and validated. That feature is actually meant to prevent exactly what you tried to use it for - submitting via curl.
